version: '3.3'

services:
#  app:
#    container_name: spring-rest-api
#    build: .
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network
#    depends_on:
#      - postgres
#      - redis

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: events

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge