# Application properties file in yaml format
server:
  servlet:
    # defines url prefix
    context-path: /octo-events
  # defines port to run
  port: 8080
spring:
  main:
    # desables spring logo on console
    banner-mode: 'off'
    
    
# datasource
  datasource:
## default connection pool
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
### PostgreSQL
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

    
##drop n create table again, good for testing, comment this in production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false 
    hibernate:
      ddl-auto: update
# Cache
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
      
      